version: "3.8"

services:
  app:
    build:
      context: .
    container_name: "blog-app"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./configs:/app/configs
  postgres:
    image: postgres:latest
    container_name: "blog-db"
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432/tcp"
    restart: on-failure
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "app", "-U", "app"  ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres:
    driver: local