version: "3.8"

services:
  app:
    build:
      context: .
    container_name: "blog-app"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./configs:/app/configs
    command: "app web:start"
    depends_on: [postgres, redis]
  postgres:
    image: postgres:16-alpine
    container_name: "blog-db"
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432/tcp"
    restart: on-failure
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "app", "-U", "app" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: "blog-redis"
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 5s
      timeout: 5s

volumes:
  postgres:
    driver: local
  redis:
    driver: local
