base_template_path: "web/templates/base.html"
nav_bar:
  - name: "home"
    display_name: "HOME"
    uri: "/"
    content_file: "web/content/home.html"
  - name: "blog"
    display_name: "BLOG"
    uri: "/blog"
    content_file: "web/content/blog.html"
  - name: "about"
    display_name: "ABOUT"
    uri: "/about"
    content_file: "web/content/about.html"
  - name: "contact"
    display_name: "CONTACT"
    uri: "/contact"
    content_file: "web/content/contact.html"
  - name: "webhook"
    display_name: "WEBHOOK"
    uri: "/webhook"
    content_file: "web/content/webhook.html"
error_pages:
  - name: "404"
    content_file: "web/content/404.html"