layout: "web/content/parts/layout.html"
nav_path: "web/content/parts/navigation.html"
file_path: "web/content/%s.html"
error_file_path: "web/content/errors/%d.html"
pages:
  - "home"
  - "blog"
  - "about"
  - "contact"
  - "webhook"
